### ISSUE TITLE
`AssetId::non_zero` Always Returns True

### ISSUE THREAD

**Issue by partylikeits1983** [burralabs/ruscet-contracts#31]
# `AssetId::non_zero` Always Returns True

Severity: Low
Type: Logic flaw

Description:
The non_zero method in the AssetId struct always returns true, regardless of whether the AssetId is zero or non-zero. This is due to the hardcoded true value in the method, rather than performing the intended comparison logic.

https://github.com/burralabs/ruscet-contracts/blob/5b9b469773fa0feb73141658933cbc192b57ecb7/contracts/helpers/src/zero.sw#L31
```rust
impl AssetId {
    pub fn non_zero(self) -> bool {
        // self != AssetId::from(ZERO)
        true
    }
}
```

### Recommendation

Uncomment or implement the comparison logic to check if self is equal to the zero value of AssetId.

```rust
impl AssetId {
    pub fn non_zero(self) -> bool {
        self != AssetId::from(ZERO)
    }
}

```

**Comment by theausicist** [comment]
great catch, but unfortunately like a couple of the other informational issues you found earlier, this breaks compiler inlining. In this particular scenario, the AssetId.non_zero() call is only used once in the `set_asset_config` method and it's equivalent to removing this check entirely. imo, it's not a big deal to verify if the asset is ZERO because it's not public and the tx would just revert elsewhere in the fn. Explicitely removing this check however _also_ breaks the inlining, so it's a deliciate situation here that I'll label as a TODO when the compiler is more stable. Thanks!
